title: "Meine persönliche Website"
description: "Hier entsteht meine neue Seite."
remote_theme: "mmistakes/minimal-mistakes@4.28.0"
baseurl: "/blog"
url: "https://biczycki.github.io"
repository: "biczycki/blog"
include: ["_posts"]

plugins:
  - jekyll-include-cache
  - jekyll-paginate-v2 # <-- WICHTIG: Version v2 nutzen!

# Die neuen Einstellungen für das v2-Plugin:
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true
