title: ""
description: "...wenn schon Judenhass, dann wenigsten mit Vertand!"
theme: minima

# HIER KORRIGIEREN:
baseurl: "/blog"
url: "https://biczycki.github.io" 

plugins:
  - jekyll-feed

future: true
