title: "Mein Pro-Semitischer Blog"
description: "Wenn schon Judenhass, dann bitte ohne Stuss!"

# Das stabilste Standard-Theme für Beitragslisten verwenden
theme: minima

baseurl: "/blog"
url: "https://github.io" 

plugins:
  - jekyll-feed

future: true
